[package]
name = "stage3"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = {path = "../shared"}
bincode.workspace = true
serde-pickle.workspace = true
uuid.workspace = true
plotters.workspace = true