[package]
name = "stage10"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = {path = "../shared", features = ["point-explorer"]}
petgraph.workspace = true
bincode.workspace = true
uuid.workspace = true
plotters.workspace = true
clap.workspace = true
anyhow.workspace = true