[package]
name = "shared"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
uuid.workspace = true
chrono.workspace = true
opendal = { workspace = true, optional = true }
anyhow = {workspace = true, optional = true}

[features]
default = []
opendal-ext = ["opendal", "anyhow"]